config/routes.rb
PizzaioloCa::Application.routes.draw do

  get '/pages/community_involvement', to: redirect('/pages/community_programs', status: 301)
  get '/customer_services/', to: redirect('/customer_services/new', status: 301)
  get '/customer_reviews/' => 'customer_services#new', :as => :customer_new_review
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match 'orders/email_test' => 'orders#email_test', :as => :email_test
  match 'locations/clear_location' => 'locations#clear_location', :as => :locations_clear_location
  resources :locations

  get 'late-night-locations', to: "locations#late_night_index", as: "late_night_locations"
  
  resources :franchise_enquiries, :only => [:create]
  
  resources :customer_services, :only => [:index, :new, :create, :show]
  
  #resources :pizza_contest_votes, :only => [:index, :new, :create, :show]
  
  resources :orders_for_pickup, :only => [:index]
  
  
  resources :orders_for_delivery
  
  
  
  resources :admins, :only => [:index]

  namespace :api do
    namespace :v1 do
      resources :orders, only: [:show] do
        member do
          post :acknowledge
        end
      end
      resources :menu
    end
  end
  
  
  # ADMIN routes
  
  match "admins/yesterdays_orders/download" => "admins/yesterdays_orders#download", :as => :download_yesterdays_orders
  match "admins/yesterdays_orders/download_date" => "admins/yesterdays_orders#download_date", :as => :download_date_orders
  match "admins/order_printer_status/:id/send_test_to_printer" => "admins/order_printer_status#send_test_to_printer", :as => :admins_order_printer_status_send_test_to_printer
  
  namespace :admins do
    resources :admins
    resources :pizza_presets, param: :slug
    resources :calzone_presets
    resources :franchise_locations
    resources :salads
    resources :garlic_breads
    resources :cannolis
    resources :beverages
    resources :toppings
    resources :flyers
    resources :yesterdays_orders
    resources :todays_orders
    resources :ad_boxes
    resources :discount_codes
    resources :discount_code_filters
    resources :order_printer_status, :only => [:index]
  end
  
  
  
  
  # CUSTOMER routes
  
  
  
  
  resources :customers, :only => [:index]  
  namespace :customers do
    resources :customers
    resources :orders
  end
  
  namespace :franchise_locations do
    resources :printer_tests
    resources :kml_views, :only => [:show, :index]  
  end


  
  # create a new order form an old one...
  match "customers/orders/:id/new_order_from_old" => "customers/orders#new_order_from_old", :as => :customers_orders_new_order_from_old
  match "customers/orders/:id/remove_address" => "customers/orders#remove_address", :as => :customers_orders_remove_address
  
  
  
  
  # set location to use for ordering
  match 'locations/:id/set_location' => 'locations#set_location', :as => "locations_set_location"
  
  match 'order_items/live_calculate' => 'order_items#live_calculate', :as => :order_items_live_calculate
  match 'order_items/deal_live_calculate' => 'order_items#deal_live_calculate', :as => :order_items_deal_live_calculate
  
  match 'orders/live_calculate_additional_items' => 'orders#live_calculate_additional_items', :as => :orders_live_calculate_additional_items
  match 'orders/live_calculate_additional_for_combo_items' => 'orders#live_calculate_additional_for_combo_items', :as => :orders_live_calculate_additional_for_combo_items
  
  match 'orders/pickup' => 'orders#pickup', :as => :orders_pickup
  
  # only used for testing internally
  match 'orders/print_order' => 'orders#print_order', :as => :orders_print_order
  
  match 'orders/delivery' => 'orders#delivery', :as => :orders_delivery
  match 'orders/order-online' => 'orders#index', :as => :order_online
  match 'orders/menu' => 'orders#index', :as => :index
  match 'orders' => 'orders#index', :as => :orders_index
  match 'orders/pizza/:slug' => 'orders#index', :as => :orders_slug
  match 'orders/calzone/:calzone_slug' => 'orders#index', :as => :orders_calzone
  # match 'orders/deals/:deals_slug' => 'orders#index', :as => :orders_deals
  match 'orders/delicious_events' => 'orders#catering', :as => :orders_catering
  match 'order_items/pizza_size_prices' => 'order_items#pizza_size_prices', :as => :pizza_size_prices
  
  match 'orders/pickup_address' => 'orders#pickup_address', :as => :orders_pickup_address
  match 'orders/delivery_address' => 'orders#delivery_address', :as => :orders_delivery_address
  
  match 'orders/generate_customer' => 'orders#generate_customer', :as => :orders_generate_customer
  
  match 'orders/add_delivery_address' => 'orders#add_delivery_address', :as => :orders_add_delivery_address
  match 'orders/add_pickup_address' => 'orders#add_pickup_address', :as => :orders_add_pickup_address
  
  match 'orders/define_delivery_time' => 'orders#define_delivery_time', :as => :orders_define_delivery_time
  match 'orders/define_pickup_time' => 'orders#define_pickup_time', :as => :orders_define_pickup_time
  
  
  
  match 'orders/choose_pickup_location' => 'orders#choose_pickup_location', :as => :orders_choose_pickup_location
  match 'orders/:id/set_pickup_location' => 'orders#set_pickup_location', :as => :orders_set_pickup_location
  
  
  match 'orders/deals/:slug' => 'orders#create_deal', :as => :orders_slug_deal
  
  match 'orders/update_order_with_delivery_address' => 'orders#update_order_with_delivery_address', :as => :orders_update_order_with_delivery_address

  match 'orders/update_order_with_pickup_address' => 'orders#update_order_with_pickup_address', :as => :orders_update_order_with_pickup_address
  
  match 'orders/check_delivery_times_and_goto_summary' => 'orders#check_delivery_times_and_goto_summary', :as => :orders_check_delivery_times_and_goto_summary

  match 'orders/order_asap' => 'orders#order_asap', :as => :orders_order_asap

  match 'orders/order_asap_check' => 'orders#order_asap_check', :as => :orders_order_asap_check
  
  # order summary before committing
  match 'orders/summary' => 'orders#summary', :as => :orders_summary
  
  # apply discount code on summay page
  match 'orders/:order_id/apply_discount_code' => 'orders#apply_discount_code', :as => :orders_apply_discount_code

  # remove discount code from summay page
  match 'orders/:order_id/remove_discount_code' => 'orders#remove_discount_code', :as => :orders_remove_discount_code

  #order thanks for ordering
  match 'orders/thanks' => 'orders#thanks', :as => :orders_thanks
  
  # set the customer delivery time
  match 'orders/set_delivery_time' => 'orders#set_delivery_time', :as => :orders_set_delivery_time
  
  # set the order to be delivered ASAP
  match 'orders/set_delivery_time_asap' => 'orders#set_delivery_time_asap', :as => :orders_set_delivery_time_asap
  
  
  # submit the order and go to the thankyou page...
  match 'orders/submit_order' => 'orders#submit_order', :as => :orders_submit_order
  
  # submit the order and go to the thankyou page...
  match 'orders/thankyou' => 'orders#thankyou', :as => :orders_thankyou

  # check whether printer online or not
  match 'orders/printer_status' => 'orders#printer_status', :as => :orders_printer_status
  
  match 'orders/:product_type/:id/add_item_from_menu' => 'orders#add_item_from_menu', :as => :orders_add_item_from_menu
  
  match 'orders/set_percentage_tip' => 'orders#set_percentage_tip', :as => :orders_set_percentage_tip
  match 'orders/clear_tip' => 'orders#clear_tip', :as => :orders_clear_tip

  match 'orders/details' => 'orders#details', :as => :details
  match 'orders/complete_meal' => 'orders#complete_meal', :as => :complete_meal
  match 'orders/specials' => 'orders#specials', :as => :specials
  match 'orders/additional_items' => 'orders#additional_items', :as => :additional_items
  resources :orders, except: [:show]

  match 'orders/get_customer_details' => 'orders#get_customer_details', :as => :get_customer_details
  
  match 'orders/add_additional_to_order' => 'orders#add_additional_to_order', :as => :add_additional_to_order
  match 'orders/:item_type/:item/remove_additional' => 'orders#remove_additional', :as => :orders_remove_additional
  match 'orders/cancel_add_additional_to_order' => 'orders#cancel_add_additional_to_order', :as => :orders_cancel_add_additional_to_order
  match 'orders/:slug/categories' => 'orders#categories', :as => :categories


  
  match 'orders/get_delivery_times' => 'orders#get_delivery_times', :as => :orders_get_delivery_times
  match 'orders/:id/update_order_additional_quantity_details' => 'orders#update_order_additional_quantity_details', :as => :order_update_order_additional_quantity_details
  match 'orders/:id/update_deal_quantity' => 'orders#update_deal_quantity', :as => :orders_update_deal_quantity
  
  
  
  resources :order_items

  match 'order_items/:id/update_quantity' => 'order_items#update_quantity', :as => :otder_item_update_quantity
  match 'order_items/:id/update_quantity_details' => 'order_items#update_quantity_details', :as => :order_item_update_quantity_details
  match 'order_items/:id/change_pizza_size_details' => 'order_items#change_pizza_size_details', :as => :order_item_change_pizza_size_details
  
  match 'order_items/add_or_update' => 'order_items#add_or_update', :as => :add_or_update_order_item
  
  match 'orders/add_product' => 'orders#add_product', :as => :add_product
  
  root :to => 'home#index'
  
  
  
  
  # devise login routes
  devise_for :customers, :controllers => {:sessions => "customers/sessions", :registrations => "customers/registrations"}
  devise_for :admins
  
  
  # sidekiq monitoring
  require 'sidekiq/web'
  
  # config/routes.rb
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.

app/controllers/admins/pizza_presets_controller.rb
class Admins::PizzaPresetsController < ApplicationController
  
  before_filter :authenticate_admin!
  layout  "admin"
  
  def index
    @pizza_presets = PizzaPreset.order("product_name ASC")
  end
  
  def edit
    @pizza_preset = PizzaPreset.find_by_slug(params[:id])
  end
  
  def update
    @pizza_preset = PizzaPreset.find_by_slug(params[:id])
    
    params[:pizza_preset][:product_info] = params[:product]
    params[:pizza_preset][:product_info][:product_name] = params[:pizza_preset][:product_name]
    params[:pizza_preset][:product_info][:product_type] = 'pizza'
    params[:pizza_preset][:product_info][:pizza_preset_id] = @pizza_preset.id
    
    if @pizza_preset.update_attributes(params[:pizza_preset])
      redirect_to admins_pizza_presets_path, :notice => "Pizza Prest Updated"
    else
      flash[:notice] = "There was a problem updating the preset"
      render :edit
    end
    # expire_fragment("pizza_selection")
    # @pizza_preset.update_attributes(params[:pizza_preset])
  end
  
  def new
    
    # use the create your own as a base pizza to generate the new one...
    @pizza_category = PizzaCategory.where(:direct_edit => true).first
    @base_pizza = @pizza_category.pizza_presets.first
    @pizza_preset = PizzaPreset.new
    @pizza_preset.product_info = @base_pizza.product_info
    
  end
  
  def create

    @pizza_preset = PizzaPreset.new(params[:pizza_preset])
    @pizza_preset.save
    
    # save the setup of the pizza
    params[:pizza_preset][:product_info] = params[:product]
    params[:pizza_preset][:product_info][:product_name] = params[:pizza_preset][:product_name]
    params[:pizza_preset][:product_info][:product_type] = 'pizza'
    params[:pizza_preset][:product_info][:pizza_preset_id] = @pizza_preset.id
    
    if @pizza_preset.update_attributes(params[:pizza_preset])
      redirect_to admins_pizza_presets_path, :notice => "Saved the Pizza Preset"
    else
      render :new
    end
    
    # expire_fragment("pizza_selection")
    
  end
  
  def destroy
    @pizza_preset = PizzaPreset.find_by_slug(params[:id])
    @pizza_preset.destroy
    # expire_fragment("pizza_selection")
    redirect_to admins_pizza_presets_path, :notice => "Pizza Preset Deleted"
  end
  
  
end

app/helpers/admins/pizza_presets_helper.rb
module Admins::PizzaPresetsHelper
end

app/views/admins/pizza_presets/_form.html.slim
.body-container
	.container
		= simple_form_for([:admins, @pizza_preset], multipart: true) do |f|

			input name="product[product_type]" type="hidden" value="pizza"
			
			fieldset
				legend Product Details
			
				=f.input :product_name, :required => true
				
				=f.input :active, :label => "Show Pizza in the Order Menu"
				
				=f.input :show_images, :label => "Show Product Images"
				
				=f.input :gluten_free_only, :label => "Set Product to be 'Gluten Free' Only"

				=f.input :is_product_combo, :label => "Is Product Combo"

				=f.input :is_10_inches, :label => "Is 10 inches only"

				=f.input :is_new_pizza, :label => "Is New Pizza Preset"

				=f.input :sort, :label => "Sort Order"

				=f.input :product_combo_id, :label => "Product Combo", collection: ProductCombo.all.map {|pc| [pc.title, pc.id]} 
				
				=f.association :pizza_category, include_blank: false
				
				hr
				
				=f.input :pizzaiolo_favourites
				=f.input :spicy
				=f.input :customer_favourites
				=f.input :vegan
				=f.input :health_check
				=f.input :nut_free
				=f.input :calories
				=f.input :description	
				=f.input :tag_list, :label => "Tags (separated by commas)"
			
			fieldset
			
				legend Product Images
			
				
				=f.input :pizza_image_flat, :as => :file, :required => true, :label => "Upload/Replace Product Image (flat)"
				- unless @pizza_preset.pizza_image_flat.blank? 
					= image_tag @pizza_preset.pizza_image_flat.size_800.url
				hr
				
					
				/ =f.input :image_flat, :as => :file, :required => true, :label => "Product Image (angled)"
				
				=f.input :pizza_image_angled, :as => :file, :required => true, :label => "Upload/Replace Product Image (angled)"
				- unless @pizza_preset.pizza_image_angled.blank?
					= image_tag @pizza_preset.pizza_image_angled.size_800.url
			
				br
				
				br
			
			/ input name="product[product_name]" class=""
			
			legend Pizza Setup
			
			.row

				.span4
					h3 Select Size

					fieldset
						- PizzaSize.where(:active => true).each do |pizza_size|
							label.radio
								- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['pizza_size'].present? && @pizza_preset.product_info['pizza_size'] == pizza_size.name.parameterize
									input type="radio" name="product[pizza_size]" value="#{pizza_size.name.parameterize}" id="product_pizza_size" topping-price=number_to_currency(pizza_size.topping_price) checked=""
								- else
									input type="radio" name="product[pizza_size]" value="#{pizza_size.name.parameterize}" id="product_pizza_size" topping-price=number_to_currency(pizza_size.topping_price)
								= pizza_size.name
						
				.span3#product_pizza_size_group class="#{unless @pizza_preset then "hideit" end}"
					h3 Select Crust
					fieldset
						- PizzaCrust.where(:active => true).order("name ASC").each do |pizza_crust|
							label.radio
								- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['pizza_crust'].present? && @pizza_preset.product_info['pizza_crust'] == pizza_crust.name.parameterize
									input type="radio" name="product[pizza_crust]" value="#{pizza_crust.name.parameterize}" id="product_pizza_crust" checked=""
								- else
									input type="radio" name="product[pizza_crust]" value="#{pizza_crust.name.parameterize}" id="product_pizza_crust"
								= pizza_crust.name
				
				span5#product_pizza_crust_style_group class="#{if @pizza_preset && @pizza_preset.product_info['pizza_size'].present? && @pizza_preset.product_info['pizza_size'] == 'gluten-free' then 'hide' end}"
								h3 Select Crust Style
								fieldset
							
									- PizzaCrustStyle.where(:active => true).order("position ASC").each do |pizza_crust_style|
							
										label.radio
											- if @pizza_preset && @pizza_preset.product_info['pizza_crust_style'] && @pizza_preset.product_info['pizza_crust_style'] == pizza_crust_style.name.parameterize
												input type="radio" name="product[pizza_crust_style]" value="#{pizza_crust_style.name.parameterize}" id="pizza_crust_style" checked=""
											- else
												input type="radio" name="product[pizza_crust_style]" value="#{pizza_crust_style.name.parameterize}" id="product_pizza_crust_style"
											= pizza_crust_style.name
							
									#deep_dish_option_price class="#{if @pizza_preset && @pizza_preset.product_info['pizza_size'].present? && @pizza_preset.product_info['pizza_size'] == 'gluten-free' || !@pizza_preset.product_info['pizza_crust_style'].present? then 'hideit' end}"
										small 
											p.muted
												| Deep Dish option adds: 
												span#deep_dish_option_price
													/ - if @pizza_preset && @pizza_preset.product_info['pizza_size'].present?
													/ 	= number_to_currency(@pizza_preset.)
				
			.row 
				.span6 class="#{unless @pizza_preset then "hideit" end}"
					h3 Special Instructions
					<br />
					fieldset
						- PizzaSpecialInstruction.active.order("position ASC").each do |pizza_sp|
							label.radio
								- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['special_instructions'].present? && @pizza_preset.product_info['special_instructions'] == pizza_sp.name.parameterize
									input type="radio" name="product[special_instructions]" value="#{pizza_sp.name.parameterize}" id="product_special_instructions" checked=""
								- else
									input type="radio" name="product[special_instructions]" value="#{pizza_sp.name.parameterize}" id="product_special_instructions"
								= pizza_sp.name


			.row#product_toppings_group class="#{unless @pizza_preset then 'hideit' end}"

				.span12
					<br />
					h3
						| Select Toppings
						- unless @pizza_preset
							small Step 3 of 5

				.clear

				- TypeOfTopping.where(:active => true).order("name ASC").each do |type_of_topping|
					.span2.toppings
						legend= type_of_topping.name
						- type_of_topping.toppings.where(:active => true).order("name ASC").each do |topping|
					
							div id=topping.name.parameterize
							
								input name="product[toppings][topping-#{topping.id}][id]" type="hidden" value="#{topping.id}"
								input name="product[toppings][topping-#{topping.id}][name]" type="hidden" value="#{topping.name}"
					
								label.checkbox.small
									- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['selected'] == "1"
										- selected = true
										input.hideshow_topping type="checkbox" id="product_toppings_topping-#{topping.id}_selected" name="product[toppings][topping-#{topping.id}][selected]" value="1" checked="" data-topping-id="#{topping.id}"
									- else
										- selected = false
										input.hideshow_topping type="checkbox" id="product_toppings_topping-#{topping.id}_selected" name="product[toppings][topping-#{topping.id}][selected]" value="1" data-topping-id="#{topping.id}"
									= topping.name
									| <br />
									- if topping.free_topping?
										small	free
									- else
										small.topping_price= "$0.00"
							
								- pref = topping.name.parameterize + "-preference"
								select.span2.small id="product_toppings_topping-#{topping.id}_preference" name="product[toppings][topping-#{topping.id}][preference]" class="#{unless selected == true then 'hideit' end}" data-topping-preference-id="#{topping.id}"
									
									- if topping.type_of_topping.preference_normal?
										- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Normal"
											option selected="selected"
												| Normal
										- else
											option Normal
									- if topping.type_of_topping.preference_light?
										- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Light"
											option selected="selected"
												| Light
										- else
											option Light
									- if topping.type_of_topping.preference_extra?
										- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Extra"
											option selected="selected"
												| Extra
										- else
											option Extra
									//- if topping.type_of_topping.preference_double? && @pizza_preset.present? && @pizza_preset.is_product_combo
									- if topping.type_of_topping.preference_double? && @pizza_preset.present?
										- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Double"
											option selected="selected"
												| Double
										- else
											option Double
								
								
								- position = topping.name.parameterize + "-position"
								select.span2.small id="product_toppings_topping-#{topping.id}_position" name="product[toppings][topping-#{topping.id}][position]" class="#{unless selected == true then 'hideit' end}" data-topping-position-id="#{topping.id}"
									- position_arr = ["Whole Pizza","Left Side","Right Side"]
									- position_arr.each do |pos|
										- if !@pizza_preset.product_info.blank? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['position'].present? && @pizza_preset.product_info['toppings']["topping-#{topping.id}"]['position'] == pos
											option selected="selected"
												= pos
										- else
											option
												=pos

			hr
				= f.button :submit, "Save/Update This Pizza", :class => "btn-green"
				
				= " "
				
				= link_to "Cancel", admins_pizza_presets_path, :class => "btn"
				
				

app/views/admins/pizza_presets/edit.html.slim
.page-header

	h1 Edit Pizza Preset
	
	p.lead From here you can edit an existing pizza product to show up in the ordering system and throughout the site.

= render(:partial => 'admins/pizza_presets/form')

app/views/admins/pizza_presets/index.html.slim
.container
	.body-container
		.page-header
			h1 Pizzas
			
		table.table.table-striped
			thead
				tr
					th Name Of Product
					th 
					th Categorized Under
					th Tagged
					th Show in menu
					th.text-center Options
			tbody
				- @pizza_presets.each do |pizza_preset|
					
					tr
						td= pizza_preset.product_name
						td=image_tag pizza_preset.pizza_image_angled.thumbnail.url
						td= pizza_preset.pizza_category.name
						td
							- if pizza_preset.pizzaiolo_favourites?
								| Favourite 
							- if pizza_preset.spicy?
								| Spicy 
							- if pizza_preset.customer_favourites?
								| Cusomter Favourite 
							- if pizza_preset.vegan?
								| Vegan 
							- if pizza_preset.health_check?
								| Health Check 
						td
							- if pizza_preset.active?
								| Yes
							- else
								| No
						td.text-center 
							= link_to "Edit", edit_admins_pizza_preset_path(pizza_preset.slug), :class => "btn btn-mini"
							= " "
							= link_to "Delete", admins_pizza_preset_path(pizza_preset.id), :class => "btn btn-mini btn-danger", :method => :delete, :confirm => "Are you sure?"

		hr

		.text-center
			= link_to "New Pizza", new_admins_pizza_preset_path, :class => "btn-green"

app/views/admins/pizza_presets/new.html.slim
.page-header

	h1 Create Pizza Preset
	
	p.lead From here you can create a new pizza product to show up in the ordering system and throughout the site.

= render(:partial => 'admins/pizza_presets/form')