config/routes.rb
  get '/pages/community_involvement', to: redirect('/pages/community_programs', status: 301)
  get '/customer_services/', to: redirect('/customer_services/new', status: 301)
  get '/customer_reviews/' => 'customer_services#new', :as => :customer_new_review
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match 'orders/email_test' => 'orders#email_test', :as => :email_test
  match 'locations/clear_location' => 'locations#clear_location', :as => :locations_clear_location
  resources :locations

  get 'late-night-locations', to: "locations#late_night_index", as: "late_night_locations"
  
  resources :franchise_enquiries, :only => [:create]
  
  resources :customer_services, :only => [:index, :new, :create, :show]
  
  #resources :pizza_contest_votes, :only => [:index, :new, :create, :show]
  
  resources :orders_for_pickup, :only => [:index]
  
  
  resources :orders_for_delivery
  
  
  
  resources :admins, :only => [:index]

  namespace :api do
    namespace :v1 do
      resources :orders, only: [:show] do
        member do
          post :acknowledge
        end
      end
      resources :menu
    end
  end
  
  
  # ADMIN routes
  
  match "admins/yesterdays_orders/download" => "admins/yesterdays_orders#download", :as => :download_yesterdays_orders
  match "admins/yesterdays_orders/download_date" => "admins/yesterdays_orders#download_date", :as => :download_date_orders
  match "admins/order_printer_status/:id/send_test_to_printer" => "admins/order_printer_status#send_test_to_printer", :as => :admins_order_printer_status_send_test_to_printer
  
  namespace :admins do
    resources :admins
    resources :pizza_presets, param: :slug
    resources :calzone_presets
    resources :franchise_locations
    resources :salads
    resources :garlic_breads
    resources :cannolis
    resources :beverages
    resources :toppings
    resources :flyers
    resources :yesterdays_orders
    resources :todays_orders
    resources :ad_boxes
    resources :discount_codes
    resources :discount_code_filters
    resources :order_printer_status, :only => [:index]
  end
  
  
  
  
  # CUSTOMER routes
  
  
  
  
  resources :customers, :only => [:index]  
  namespace :customers do
    resources :customers
    resources :orders
  end
  
  namespace :franchise_locations do
    resources :printer_tests
    resources :kml_views, :only => [:show, :index]  
  end


  
  # create a new order form an old one...
  match "customers/orders/:id/new_order_from_old" => "customers/orders#new_order_from_old", :as => :customers_orders_new_order_from_old
  match "customers/orders/:id/remove_address" => "customers/orders#remove_address", :as => :customers_orders_remove_address
  
  
  
  
  # set location to use for ordering
  match 'locations/:id/set_location' => 'locations#set_location', :as => "locations_set_location"
  
  match 'order_items/live_calculate' => 'order_items#live_calculate', :as => :order_items_live_calculate
  match 'order_items/deal_live_calculate' => 'order_items#deal_live_calculate', :as => :order_items_deal_live_calculate
  
  match 'orders/live_calculate_additional_items' => 'orders#live_calculate_additional_items', :as => :orders_live_calculate_additional_items
  match 'orders/live_calculate_additional_for_combo_items' => 'orders#live_calculate_additional_for_combo_items', :as => :orders_live_calculate_additional_for_combo_items
  
  match 'orders/pickup' => 'orders#pickup', :as => :orders_pickup
  
  # only used for testing internally
  match 'orders/print_order' => 'orders#print_order', :as => :orders_print_order
  
  match 'orders/delivery' => 'orders#delivery', :as => :orders_delivery
  match 'orders/order-online' => 'orders#index', :as => :order_online
  match 'orders/menu' => 'orders#index', :as => :index
  match 'orders' => 'orders#index', :as => :orders_index
  match 'orders/pizza/:slug' => 'orders#index', :as => :orders_slug
  match 'orders/calzone/:calzone_slug' => 'orders#index', :as => :orders_calzone
  # match 'orders/deals/:deals_slug' => 'orders#index', :as => :orders_deals
  match 'orders/delicious_events' => 'orders#catering', :as => :orders_catering
  match 'order_items/pizza_size_prices' => 'order_items#pizza_size_prices', :as => :pizza_size_prices
  
  match 'orders/pickup_address' => 'orders#pickup_address', :as => :orders_pickup_address
  match 'orders/delivery_address' => 'orders#delivery_address', :as => :orders_delivery_address
  
  match 'orders/generate_customer' => 'orders#generate_customer', :as => :orders_generate_customer
  
  match 'orders/add_delivery_address' => 'orders#add_delivery_address', :as => :orders_add_delivery_address
  match 'orders/add_pickup_address' => 'orders#add_pickup_address', :as => :orders_add_pickup_address
  
  match 'orders/define_delivery_time' => 'orders#define_delivery_time', :as => :orders_define_delivery_time
  match 'orders/define_pickup_time' => 'orders#define_pickup_time', :as => :orders_define_pickup_time
  
  
  
  match 'orders/choose_pickup_location' => 'orders#choose_pickup_location', :as => :orders_choose_pickup_location
  match 'orders/:id/set_pickup_location' => 'orders#set_pickup_location', :as => :orders_set_pickup_location
  
  
  match 'orders/deals/:slug' => 'orders#create_deal', :as => :orders_slug_deal
  
  match 'orders/update_order_with_delivery_address' => 'orders#update_order_with_delivery_address', :as => :orders_update_order_with_delivery_address

  match 'orders/update_order_with_pickup_address' => 'orders#update_order_with_pickup_address', :as => :orders_update_order_with_pickup_address
  
  match 'orders/check_delivery_times_and_goto_summary' => 'orders#check_delivery_times_and_goto_summary', :as => :orders_check_delivery_times_and_goto_summary

  match 'orders/order_asap' => 'orders#order_asap', :as => :orders_order_asap

  match 'orders/order_asap_check' => 'orders#order_asap_check', :as => :orders_order_asap_check
  
  # order summary before committing
  match 'orders/summary' => 'orders#summary', :as => :orders_summary
  
  # apply discount code on summay page
  match 'orders/:order_id/apply_discount_code' => 'orders#apply_discount_code', :as => :orders_apply_discount_code

  # remove discount code from summay page
  match 'orders/:order_id/remove_discount_code' => 'orders#remove_discount_code', :as => :orders_remove_discount_code

  #order thanks for ordering
  match 'orders/thanks' => 'orders#thanks', :as => :orders_thanks
  
  # set the customer delivery time
  match 'orders/set_delivery_time' => 'orders#set_delivery_time', :as => :orders_set_delivery_time
  
  # set the order to be delivered ASAP
  match 'orders/set_delivery_time_asap' => 'orders#set_delivery_time_asap', :as => :orders_set_delivery_time_asap
  
  
  # submit the order and go to the thankyou page...
  match 'orders/submit_order' => 'orders#submit_order', :as => :orders_submit_order
  
  # submit the order and go to the thankyou page...
  match 'orders/thankyou' => 'orders#thankyou', :as => :orders_thankyou

  # check whether printer online or not
  match 'orders/printer_status' => 'orders#printer_status', :as => :orders_printer_status
  
  match 'orders/:product_type/:id/add_item_from_menu' => 'orders#add_item_from_menu', :as => :orders_add_item_from_menu
  
  match 'orders/set_percentage_tip' => 'orders#set_percentage_tip', :as => :orders_set_percentage_tip
  match 'orders/clear_tip' => 'orders#clear_tip', :as => :orders_clear_tip

  match 'orders/details' => 'orders#details', :as => :details
  match 'orders/complete_meal' => 'orders#complete_meal', :as => :complete_meal
  match 'orders/specials' => 'orders#specials', :as => :specials
  match 'orders/additional_items' => 'orders#additional_items', :as => :additional_items
  resources :orders, except: [:show]

  match 'orders/get_customer_details' => 'orders#get_customer_details', :as => :get_customer_details
  
  match 'orders/add_additional_to_order' => 'orders#add_additional_to_order', :as => :add_additional_to_order
  match 'orders/:item_type/:item/remove_additional' => 'orders#remove_additional', :as => :orders_remove_additional
  match 'orders/cancel_add_additional_to_order' => 'orders#cancel_add_additional_to_order', :as => :orders_cancel_add_additional_to_order
  match 'orders/:slug/categories' => 'orders#categories', :as => :categories


  
  match 'orders/get_delivery_times' => 'orders#get_delivery_times', :as => :orders_get_delivery_times
  match 'orders/:id/update_order_additional_quantity_details' => 'orders#update_order_additional_quantity_details', :as => :order_update_order_additional_quantity_details
  match 'orders/:id/update_deal_quantity' => 'orders#update_deal_quantity', :as => :orders_update_deal_quantity
  
  
  
  resources :order_items

  match 'order_items/:id/update_quantity' => 'order_items#update_quantity', :as => :otder_item_update_quantity
  match 'order_items/:id/update_quantity_details' => 'order_items#update_quantity_details', :as => :order_item_update_quantity_details
  match 'order_items/:id/change_pizza_size_details' => 'order_items#change_pizza_size_details', :as => :order_item_change_pizza_size_details
  
  match 'order_items/add_or_update' => 'order_items#add_or_update', :as => :add_or_update_order_item
  
  match 'orders/add_product' => 'orders#add_product', :as => :add_product
  
  root :to => 'home#index'
  
  
  
  
  # devise login routes
  devise_for :customers, :controllers => {:sessions => "customers/sessions", :registrations => "customers/registrations"}
  devise_for :admins
  
  
  # sidekiq monitoring
  require 'sidekiq/web'
  
  # config/routes.rb
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @pizzas = PizzaPreset.order("RAND()").first(12)
    @pizza_category =  PizzaCategory.where(:active => true)

    # for home page categories slider
    @fans_favourite = PizzaPreset.tagged_with(["fans_favourite", "pizza_makers_picks"], :any => true)
    @speciality_pizza = PizzaPreset.tagged_with(["speciality_pizza"], :any => true)
    # Gluten Free & Cauliflower
    @gluten_free = PizzaPreset.tagged_with(["gluten_free", "cauliflower"], :any => true)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/__index.html.slim
- content_for(:title) {"Welcome"}

- meta title: "Pizzaiolo | Gourmet Pizza | Pizza Delivery Toronto | Take Out Pizza",
	description: "Pizzaiolo prides themselves on making fresh pizza with fresh ingredients daily. Pizza delivery Toronto, best pizza delivery Toronto. Gluten-free pizza, wheat free pizza dough, thin crust pizza. Pizzaiolo is a pizza catering company, pizza delivery company, order pizza online, popular pizza.",
	keywords: "Pizzaiolo"

h1 style="display:none;" Welcome to Pizzaiolo	

.hidden-phone
	.row.homepage-headings
		.container
			h2.malbeck Our Famous Pizzaiolo Tomato Sauce and Artisan Dough are Made Fresh Daily! 
			h2.light.m-t-20 Gluten-free and wheat-free dough available	

	.row.home-pizza-presets
		.container
			div class="pizza-carousel" id="pizza-carousel"
				div class="carousel-inner"
					div class="item active"
						div class="row"
							- @pizzas[0,3].each do |pizza|
								.span4
									div.pizza-card.fixed-height
										= image_tag pizza.pizza_image_angled.size_300.url
										.details
											p.item_title = raw("#{pizza.product_name} ")
											p.calories = pizza.calories
											p = pizza.toppings.to_sentence(:last_word_connector => ' and ')
										.bottom-button
											= link_to "ORDER NOW", orders_path(:pizza_preset_id => pizza.id), :class => "button default"
								
					div class="item"
						div class="row"
							- @pizzas[3,3].each do |pizza|
								.span4
									div.pizza-card.fixed-height
										= image_tag pizza.pizza_image_angled.size_300.url
										.details	
											p.item_title = raw("#{pizza.product_name} ")
											p.calories = pizza.calories
											p = pizza.toppings.to_sentence(:last_word_connector => ' and ')
										
										.bottom-button
											= link_to "ORDER NOW", orders_path(:pizza_preset_id => pizza.id), :class => "button default"

					div class="item"
						div class="row"
							- @pizzas[6,3].each do |pizza|
								.span4
									div.pizza-card.fixed-height
										= image_tag pizza.pizza_image_angled.size_300.url
										.details
											p.item_title = raw("#{pizza.product_name} ")
											p.calories = pizza.calories
											p = pizza.toppings.to_sentence(:last_word_connector => ' and ')
										.bottom-button
											= link_to "ORDER NOW", orders_path(:pizza_preset_id => pizza.id), :class => "button default"


					div class="item"
						div class="row"
							- @pizzas[9,3].each do |pizza|
								.span4
									div.pizza-card.fixed-height
										= image_tag pizza.pizza_image_angled.size_300.url
										.details
											p.item_title = raw("#{pizza.product_name} ")
											p.calories = pizza.calories
											p = pizza.toppings.to_sentence(:last_word_connector => ' and ')
										.bottom-button
											= link_to "ORDER NOW", orders_path(:pizza_preset_id => pizza.id), :class => "button default"
				<a class="pizza-carousel-control left" href="#pizza-carousel" data-slide="prev">&lsaquo;</a>
				<a class="pizza-carousel-control right" href="#pizza-carousel" data-slide="next">&rsaquo;</a>

				.row.text-center	
					= link_to "SEE OUR FULL MENU", orders_path, class: 'block green-link'

	.ad-box
		.container
			.row
				- cache('ad_pods_homepage') do
					- AdBox.where(:active => true).order(:position).each do |ad_box|
						.span4
							- unless ad_box.url_link.blank?
								a href="#{ad_box.url_link}"
									img src="#{ad_box.pod.url}?#{ad_box.updated_at.to_i}" class="homepage-pods" alt="Ad Box Image"
							- else
								img src="#{ad_box.pod.url}?#{ad_box.updated_at.to_i}" class="homepage-pods" alt="Ad Box Image"

	div.late-night
		.container
			= link_to late_night_locations_path do 
				= image_tag 'home_page/openslate-wide.png'

app/views/home/index.html.erb
<% content_for(:title) {"Welcome"} %>

<% meta title: "Pizzaiolo | Toronto and GTA’s Gourmet Pizza | Takeout and Delivery",
	description: "Pizzaiolo prides themselves on making fresh pizza with fresh ingredients daily. A wide selection of gourmet meat, veggie, vegan and Gluten-Free pizzas. Order today!",
	keywords: "Pizzaiolo, Gourmet Pizza, Gluten Free, Pizza Delivery" %>

<!--First Section Start-->
<section class="greenborder"></section>
<section class="home-section" style="background-image: url('/assets/new_design/Background pattern.jpg'); background-repeat: no-repeat; background-size: cover;">
  <div class="home-category-thumb">
    <div class="container mobile-container">
      <div class="row no-gutters gridOrder gridCard main-menu">
        <div class="food-category">
          <a href="/orders/pizza/create-your-own-pizza">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/thumb_customize.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">CUSTOMIZE</h2>
              </div>
            </div>
          </a>
        </div>  
        <div class="food-category">
          <a href="/orders/<%= @pizza_category[0].slug %>/categories">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/thumb_meat.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">MEAT</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category">
          <a href="/orders/<%= @pizza_category[1].slug %>/categories">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/thumb_veggie.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">VEGGIE</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category">
          <a href="/orders/<%= @pizza_category[2].slug %>/categories">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/thumb_vegan.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">VEGAN</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category">
          <a href="/orders/<%= @pizza_category[4].slug %>/categories">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/new_gluten_Free.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center gulten_free_title">
                <h2 class="card-title">Gluten Free & Cauliflower</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category">
          <a href="/orders/<%= @pizza_category[5].slug %>/categories">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/plant_based_thumb.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">Plant Based</h2>
              </div>
            </div>
          </a>
        </div>
        <!--div class="food-category">
          <a href="/orders/calzone/baked-calzone">
            <div class="card border-0 rounded-0 hc-block">
              <img class="card-img rounded-0" src="/assets/new_design/calzones.jpg" alt="Card image">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">CALZONES</h2>
              </div>
            </div>
          </a>
        </div-->
      </div>
      <div class="home-content-panel page-sub-title" style="">
        <div class="row">
          <div class="col-sm-8 offset-sm-4">
            <h2>COMPLETE <br> Your MEAL</h2>
          </div>
        </div>
      </div>
      <div class="row no-gutters gridCard order-additional order-additional-mobile-style">
        <div class="food-category calzones">
          <a class="pizza_category" href="/orders/calzone/baked-calzone">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Drink_dips" src="/assets/new_design/calzones.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">CALZONES</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category beverages">
          <a href="/orders/additional_items#garlic">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Garlic_break" src="/assets/new_design/garlic_break.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">GARLIC<br>BREAD</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category salads">
          <a href="/orders/additional_items#salads">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Salad" src="/assets/new_design/salad.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">SALADS</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category calzones">
          <a class="pizza_category" href="/orders/additional_items#Bottles">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Drink_dips" src="/assets/new_design/drink_dips.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">DRINKS</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category beverages">
          <a href="/orders/additional_items#Dipping">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Dips-cat" src="/assets/new_design/dips-cat.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">DIPS</h2>
              </div>
            </div>
          </a>
        </div>
        <div class="food-category Cater">
          <a class="pizza_category" href="/orders/delicious_events">
            <div class="card border-0 rounded-0 hc-block">
              <img alt="Drink_dips" src="/assets/new_design/cater.jpg">
              <div class="card-img-overlay d-flex align-items-center justify-content-center">
                <h2 class="card-title">Catering</h2>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="home-content-panel home-content-layout">
      <div class="row">
        <div class="col-sm-2 hidden-mobile"> <img src="/assets/new_design/brand.svg" alt="" width="100px"> </div>
        <div class="col-12 col-sm-7">
          <h2>ARE YOU
            READY
            TO PIZZA?
          </h2>
          <p>Pizzaiolo has a wide selection<br> of  gourmet meat, veggie, <br> and vegan pizzas.  You can even design<br  class="hidden-mobile"> your own. All our pizzas are <br  class="hidden-mobile">available Gluten-free.</p>
        </div>
      </div>
      <div class="row mobile-align">
        <div class="col-sm-9 text-right"> 
          <%= link_to "Order", '/orders/menu', { :class=>"btn-green" } %>
        </div>
      </div>
    </div>
  </div>
</section>
<!--First Section End-->