config/routes.rb
PizzaioloCa::Application.routes.draw do

  get '/pages/community_involvement', to: redirect('/pages/community_programs', status: 301)
  get '/customer_services/', to: redirect('/customer_services/new', status: 301)
  get '/customer_reviews/' => 'customer_services#new', :as => :customer_new_review
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match 'orders/email_test' => 'orders#email_test', :as => :email_test
  match 'locations/clear_location' => 'locations#clear_location', :as => :locations_clear_location
  resources :locations

  get 'late-night-locations', to: "locations#late_night_index", as: "late_night_locations"
  
  resources :franchise_enquiries, :only => [:create]
  
  resources :customer_services, :only => [:index, :new, :create, :show]
  
  #resources :pizza_contest_votes, :only => [:index, :new, :create, :show]
  
  resources :orders_for_pickup, :only => [:index]
  
  
  resources :orders_for_delivery
  
  
  
  resources :admins, :only => [:index]

  namespace :api do
    namespace :v1 do
      resources :orders, only: [:show] do
        member do
          post :acknowledge
        end
      end
      resources :menu
    end
  end
  
  
  # ADMIN routes
  
  match "admins/yesterdays_orders/download" => "admins/yesterdays_orders#download", :as => :download_yesterdays_orders
  match "admins/yesterdays_orders/download_date" => "admins/yesterdays_orders#download_date", :as => :download_date_orders
  match "admins/order_printer_status/:id/send_test_to_printer" => "admins/order_printer_status#send_test_to_printer", :as => :admins_order_printer_status_send_test_to_printer
  
  namespace :admins do
    resources :admins
    resources :pizza_presets, param: :slug
    resources :calzone_presets
    resources :franchise_locations
    resources :salads
    resources :garlic_breads
    resources :cannolis
    resources :beverages
    resources :toppings
    resources :flyers
    resources :yesterdays_orders
    resources :todays_orders
    resources :ad_boxes
    resources :discount_codes
    resources :discount_code_filters
    resources :order_printer_status, :only => [:index]
  end
  
  
  
  
  # CUSTOMER routes
  
  
  
  
  resources :customers, :only => [:index]  
  namespace :customers do
    resources :customers
    resources :orders
  end
  
  namespace :franchise_locations do
    resources :printer_tests
    resources :kml_views, :only => [:show, :index]  
  end


  
  # create a new order form an old one...
  match "customers/orders/:id/new_order_from_old" => "customers/orders#new_order_from_old", :as => :customers_orders_new_order_from_old
  match "customers/orders/:id/remove_address" => "customers/orders#remove_address", :as => :customers_orders_remove_address
  
  
  
  
  # set location to use for ordering
  match 'locations/:id/set_location' => 'locations#set_location', :as => "locations_set_location"
  
  match 'order_items/live_calculate' => 'order_items#live_calculate', :as => :order_items_live_calculate
  match 'order_items/deal_live_calculate' => 'order_items#deal_live_calculate', :as => :order_items_deal_live_calculate
  
  match 'orders/live_calculate_additional_items' => 'orders#live_calculate_additional_items', :as => :orders_live_calculate_additional_items
  match 'orders/live_calculate_additional_for_combo_items' => 'orders#live_calculate_additional_for_combo_items', :as => :orders_live_calculate_additional_for_combo_items
  
  match 'orders/pickup' => 'orders#pickup', :as => :orders_pickup
  
  # only used for testing internally
  match 'orders/print_order' => 'orders#print_order', :as => :orders_print_order
  
  match 'orders/delivery' => 'orders#delivery', :as => :orders_delivery
  match 'orders/order-online' => 'orders#index', :as => :order_online
  match 'orders/menu' => 'orders#index', :as => :index
  match 'orders' => 'orders#index', :as => :orders_index
  match 'orders/pizza/:slug' => 'orders#index', :as => :orders_slug
  match 'orders/calzone/:calzone_slug' => 'orders#index', :as => :orders_calzone
  # match 'orders/deals/:deals_slug' => 'orders#index', :as => :orders_deals
  match 'orders/delicious_events' => 'orders#catering', :as => :orders_catering
  match 'order_items/pizza_size_prices' => 'order_items#pizza_size_prices', :as => :pizza_size_prices
  
  match 'orders/pickup_address' => 'orders#pickup_address', :as => :orders_pickup_address
  match 'orders/delivery_address' => 'orders#delivery_address', :as => :orders_delivery_address
  
  match 'orders/generate_customer' => 'orders#generate_customer', :as => :orders_generate_customer
  
  match 'orders/add_delivery_address' => 'orders#add_delivery_address', :as => :orders_add_delivery_address
  match 'orders/add_pickup_address' => 'orders#add_pickup_address', :as => :orders_add_pickup_address
  
  match 'orders/define_delivery_time' => 'orders#define_delivery_time', :as => :orders_define_delivery_time
  match 'orders/define_pickup_time' => 'orders#define_pickup_time', :as => :orders_define_pickup_time
  
  
  
  match 'orders/choose_pickup_location' => 'orders#choose_pickup_location', :as => :orders_choose_pickup_location
  match 'orders/:id/set_pickup_location' => 'orders#set_pickup_location', :as => :orders_set_pickup_location
  
  
  match 'orders/deals/:slug' => 'orders#create_deal', :as => :orders_slug_deal
  
  match 'orders/update_order_with_delivery_address' => 'orders#update_order_with_delivery_address', :as => :orders_update_order_with_delivery_address

  match 'orders/update_order_with_pickup_address' => 'orders#update_order_with_pickup_address', :as => :orders_update_order_with_pickup_address
  
  match 'orders/check_delivery_times_and_goto_summary' => 'orders#check_delivery_times_and_goto_summary', :as => :orders_check_delivery_times_and_goto_summary

  match 'orders/order_asap' => 'orders#order_asap', :as => :orders_order_asap

  match 'orders/order_asap_check' => 'orders#order_asap_check', :as => :orders_order_asap_check
  
  # order summary before committing
  match 'orders/summary' => 'orders#summary', :as => :orders_summary
  
  # apply discount code on summay page
  match 'orders/:order_id/apply_discount_code' => 'orders#apply_discount_code', :as => :orders_apply_discount_code

  # remove discount code from summay page
  match 'orders/:order_id/remove_discount_code' => 'orders#remove_discount_code', :as => :orders_remove_discount_code

  #order thanks for ordering
  match 'orders/thanks' => 'orders#thanks', :as => :orders_thanks
  
  # set the customer delivery time
  match 'orders/set_delivery_time' => 'orders#set_delivery_time', :as => :orders_set_delivery_time
  
  # set the order to be delivered ASAP
  match 'orders/set_delivery_time_asap' => 'orders#set_delivery_time_asap', :as => :orders_set_delivery_time_asap
  
  
  # submit the order and go to the thankyou page...
  match 'orders/submit_order' => 'orders#submit_order', :as => :orders_submit_order
  
  # submit the order and go to the thankyou page...
  match 'orders/thankyou' => 'orders#thankyou', :as => :orders_thankyou

  # check whether printer online or not
  match 'orders/printer_status' => 'orders#printer_status', :as => :orders_printer_status
  
  match 'orders/:product_type/:id/add_item_from_menu' => 'orders#add_item_from_menu', :as => :orders_add_item_from_menu
  
  match 'orders/set_percentage_tip' => 'orders#set_percentage_tip', :as => :orders_set_percentage_tip
  match 'orders/clear_tip' => 'orders#clear_tip', :as => :orders_clear_tip

  match 'orders/details' => 'orders#details', :as => :details
  match 'orders/complete_meal' => 'orders#complete_meal', :as => :complete_meal
  match 'orders/specials' => 'orders#specials', :as => :specials
  match 'orders/additional_items' => 'orders#additional_items', :as => :additional_items
  resources :orders, except: [:show]

  match 'orders/get_customer_details' => 'orders#get_customer_details', :as => :get_customer_details
  
  match 'orders/add_additional_to_order' => 'orders#add_additional_to_order', :as => :add_additional_to_order
  match 'orders/:item_type/:item/remove_additional' => 'orders#remove_additional', :as => :orders_remove_additional
  match 'orders/cancel_add_additional_to_order' => 'orders#cancel_add_additional_to_order', :as => :orders_cancel_add_additional_to_order
  match 'orders/:slug/categories' => 'orders#categories', :as => :categories


  
  match 'orders/get_delivery_times' => 'orders#get_delivery_times', :as => :orders_get_delivery_times
  match 'orders/:id/update_order_additional_quantity_details' => 'orders#update_order_additional_quantity_details', :as => :order_update_order_additional_quantity_details
  match 'orders/:id/update_deal_quantity' => 'orders#update_deal_quantity', :as => :orders_update_deal_quantity
  
  
  
  resources :order_items

  match 'order_items/:id/update_quantity' => 'order_items#update_quantity', :as => :otder_item_update_quantity
  match 'order_items/:id/update_quantity_details' => 'order_items#update_quantity_details', :as => :order_item_update_quantity_details
  match 'order_items/:id/change_pizza_size_details' => 'order_items#change_pizza_size_details', :as => :order_item_change_pizza_size_details
  
  match 'order_items/add_or_update' => 'order_items#add_or_update', :as => :add_or_update_order_item
  
  match 'orders/add_product' => 'orders#add_product', :as => :add_product
  
  root :to => 'home#index'
  
  
  
  
  # devise login routes
  devise_for :customers, :controllers => {:sessions => "customers/sessions", :registrations => "customers/registrations"}
  devise_for :admins
  
  
  # sidekiq monitoring
  require 'sidekiq/web'
  
  # config/routes.rb
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.

app/models/calzone_preset.rb
class CalzonePreset < ActiveRecord::Base
  
  after_update :expire_fragments
  after_create :expire_fragments

  before_save :create_or_update_slug
  
  attr_accessible :active, :calzone_image_angled, :calzone_image_flat, :product_info, :product_name, :nut_free
  serialize :product_info, JSON
  
  # upload images into the preset
  mount_uploader :calzone_image_flat, ProductImageUploader
  mount_uploader :calzone_image_angled, ProductImageUploader

  def light_topping_price
    self.normal_topping_price
  end

  def to_param
    self.slug
  end
  
  private
  
    def expire_fragments
      ActionController::Base.new.expire_fragment('calzone_preset_selection')
    end

    def create_or_update_slug
      if self.slug.nil?
        self.slug = "baked-calzone" # hard coded for now
      end
    end
  
end

app/controllers/admins/calzone_presets_controller.rb
class Admins::CalzonePresetsController < ApplicationController
  
  before_filter :authenticate_admin!
  layout  "admin"
  
  def index
    @calzone_presets = CalzonePreset.all
  end
  
  def edit
    @calzone_preset = CalzonePreset.find_by_id(params[:id])
  end
  
  def update
    @calzone_preset = CalzonePreset.find_by_id(params[:id])
    
    params[:calzone_preset][:product_info] = params[:product]
    params[:calzone_preset][:product_info][:product_name] = params[:calzone_preset][:product_name]
    params[:calzone_preset][:product_info][:product_type] = 'calzone'
    params[:calzone_preset][:product_info][:calzone_preset_id] = @calzone_preset.id
    
    if @calzone_preset.update_attributes(params[:calzone_preset])
      redirect_to admins_calzone_presets_path, :notice => "Calzone Preset Updated"
    else
      flash[:notice] = "There was a problem updating the preset"
      render :edit
    end
    @calzone_preset.update_attributes(params[:calzone_preset])
    
    # expire_fragment("calzone_selection")
    
  end
  
  
  def new
    @calzone_preset = CalzonePreset.new
  end
  
  def create

    @calzone_preset = CalzonePreset.new(params[:calzone_preset])
    @calzone_preset.save
    
    # save the setup of the calzone
    params[:calzone_preset][:product_info] = params[:product]
    params[:calzone_preset][:product_info][:product_name] = params[:calzone_preset][:product_name]
    params[:calzone_preset][:product_info][:product_type] = 'calzone'
    params[:calzone_preset][:product_info][:calzone_preset_id] = @calzone_preset.id
    
    if @calzone_preset.update_attributes(params[:calzone_preset])
      redirect_to admins_calzone_presets_path, :notice => "Saved the Calzone Preset"
    else
      render :new
    end
    
    # expire_fragment("calzone_selection")
    
  end
  
  def destroy
    @calzone_preset = CalzonePreset.find_by_id(params[:id])
    @calzone_preset.destroy
    
    # expire_fragment("calzone_selection")

    redirect_to admins_calzone_presets_path, :notice => "Calzone Presst Deleted"

  end
  
end

app/helpers/admins/calzone_presets_helper.rb
module Admins::CalzonePresetsHelper
end

app/views/admins/calzone_presets/_form.html.slim
.body-container
	.container
		= simple_form_for([:admins, @calzone_preset], multipart: true) do |f|

			input name="product[product_type]" type="hidden" value="calzone"
			
			fieldset
				legend Product Details
			
				=f.input :product_name, :required => true
				
				=f.input :active, :label => "Show Calzone in the Order Menu"
				=f.input :nut_free
				
				hr
			
			fieldset
			
				legend Product Images
			
				
				=f.input :calzone_image_flat, :as => :file, :required => true, :label => "Upload/Replace Product Image (flat)"
				- unless @calzone_preset.calzone_image_flat.blank?
					= image_tag @calzone_preset.calzone_image_flat.size_800.url
				hr

				
				=f.input :calzone_image_angled, :as => :file, :required => true, :label => "Upload/Replace Product Image (angled)"
				- unless @calzone_preset.calzone_image_angled.blank?
					= image_tag @calzone_preset.calzone_image_angled.size_800.url
			
				br
				
				br
			
			
			legend Calzone Setup
			
			.span12#product_calzone_size_group class="#{unless @calzone_preset then "hideit" end}"
				h3 Select Crust
				fieldset
					- PizzaCrust.where(:active => true).order("name ASC").each do |calzone_crust|
						label.radio
							- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['calzone_crust'].present? && @calzone_preset.product_info['calzone_crust'] == calzone_crust.name.parameterize
								input type="radio" name="product[calzone_crust]" value="#{calzone_crust.name.parameterize}" id="product_calzone_crust" checked=""
							- else
								input type="radio" name="product[calzone_crust]" value="#{calzone_crust.name.parameterize}" id="product_calzone_crust"
							= calzone_crust.name

			.row#product_toppings_group class="#{unless @calzone_preset then 'hideit' end}"

				.span12
					<br />
					h3
						| Select Toppings
						- unless @calzone_preset
							small Step 3 of 5

				.clear

				- TypeOfTopping.where(:active => true).order("name ASC").each do |type_of_topping|
					.span2.toppings
						legend= type_of_topping.name
						- type_of_topping.toppings.where(:active => true).order("name ASC").each do |topping|
					
							div id=topping.name.parameterize
							
								input name="product[toppings][topping-#{topping.id}][id]" type="hidden" value="#{topping.id}"
								input name="product[toppings][topping-#{topping.id}][name]" type="hidden" value="#{topping.name}"
					
								label.checkbox.small
									- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['selected'].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['selected'] == "1"
										- selected = true
										input.hideshow_topping type="checkbox" id="product_toppings_topping-#{topping.id}_selected" name="product[toppings][topping-#{topping.id}][selected]" value="1" checked="" data-topping-id="#{topping.id}"
									- else
										- selected = false
										input.hideshow_topping type="checkbox" id="product_toppings_topping-#{topping.id}_selected" name="product[toppings][topping-#{topping.id}][selected]" value="1" data-topping-id="#{topping.id}"
									= topping.name
									| <br />
									- if topping.free_topping?
										small	free
									- else
										small.topping_price= "$0.00"
							
								- pref = topping.name.parameterize + "-preference"
								select.span2.small id="product_toppings_topping-#{topping.id}_preference" name="product[toppings][topping-#{topping.id}][preference]" class="#{unless selected == true then 'hideit' end}" data-topping-preference-id="#{topping.id}"
									
									- if topping.type_of_topping.preference_normal?
										- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Normal"
											option selected="selected"
												| Normal
										- else
											option Normal
									- if topping.type_of_topping.preference_light?
										- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Light"
											option selected="selected"
												| Light
										- else
											option Light
									- if topping.type_of_topping.preference_extra?
										- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Extra"
											option selected="selected"
												| Extra
										- else
											option Extra
									- if topping.type_of_topping.preference_double?
										- if !@calzone_preset.product_info.blank? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"].present? && @calzone_preset.product_info['toppings']["topping-#{topping.id}"]['preference'] == "Double"
											option selected="selected"
												| Double
										- else
											option Double


			hr
				= f.button :submit, "Save/Update This Calzone", :class => "btn btn-primary"
				
				= " "
				
				= link_to "Cancel", admins_calzone_presets_path, :class => "btn"
				
				

app/views/admins/calzone_presets/edit.html.slim
.page-header

	h1 Edit Calzone Preset
	
	p.lead From here you can edit an existing calzone product to show up in the ordering system and throughout the site.

= render(:partial => 'admins/calzone_presets/form')

app/views/admins/calzone_presets/index.html.slim
.container
	.body-container
		.page-header
			h1 Calzones
			
		table.table
			thead
				tr
					th Name Of Product
					th Options
			tbody
				- @calzone_presets.each do |calzone_preset|
					tr
						td= calzone_preset.product_name
						td
							= link_to "Edit", edit_admins_calzone_preset_path(calzone_preset.id), :class => "btn btn-mini"
							= link_to "Delete", admins_calzone_preset_path(calzone_preset.id), :class => "btn btn-mini", :method => :delete
						
		hr
			
		= link_to "New Calzone", new_admins_calzone_preset_path

app/views/admins/calzone_presets/new.html.slim
.page-header

	h1 Create Calzone Preset
	
	p.lead From here you can create a new calzone product to show up in the ordering system and throughout the site.

= render(:partial => 'admins/calzone_presets/form')